ktor {
    deployment {
        port = 8080
        host = 0.0.0.0
    }
    application {
        modules = [ com.toraces.api.ApplicationKt.module ]
    }
}

jwt {
    secret = ${JWT_SECRET}
    issuer = "to-the-races"
}
